### ISSUE TITLE
slate官方demo在block末输入拼音时光标位置有问题可以解决吗？

### ISSUE THREAD

**Issue by CN-Sean** [akumatus/slate-develop-in-action#1]

**Comment by akumatus** [comment]
可以参考我提过的两个 PR：
https://github.com/ianstormtaylor/slate/pull/2454
https://github.com/ianstormtaylor/slate/pull/2455

**Comment by CN-Sean** [comment]
为什么后来close了？

**Comment by CN-Sean** [comment]
可以不修改源码slate和slate-react 解决吗?

**Comment by akumatus** [comment]
原因我在 PR 里面有说的~ 还有输入法问题是 slate-react 底层引起的，从外部没法触达。
